import "./globals.css";
import { Gothic_A1 } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const gothicA1 = Gothic_A1({
  weight: ["400", "500", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Online store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gothicA1.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
